# Exported from Render on 2024-05-07T06:12:38Z
services:
- type: web
  name: psgtechdotedu-scraping
  runtime: python
  repo: https://github.com/jassuwu/psgtechdotedu-scraping
  plan: free
  region: singapore
  buildCommand: bash init.sh
  startCommand: cd psgtechdotedu/server; uvicorn main:app --host 0.0.0.0 --port $PORT
  healthCheckPath: /health
version: "1"
