name: Redeploy to Render

on:
  schedule:
    - cron: "0 0 * * *" # This line schedules the workflow to run every day at midnight

jobs:
  redeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Redeploy
        run: curl "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"
